import type { NextPage, GetStaticProps } from "next";
import { useContext } from "react";
import Head from "next/head";
import fs from "fs/promises";
import path from "path";
import ListItem from "../components/ListItem";
import { useEffect, useState } from "react";
import FilterItem from "../components/FilterItem";
import Footer from "../components/Footer";
import { clearTagsAction, TagsContext } from "../contexts/tagsContext";

interface DataType {
  id: string;
  company: string;
  logo: string;
  new: boolean;
  featured: boolean;
  position: string;
  role: string;
  level: string;
  postedAt: string;
  contract: string;
  location: string;
  languages: string[];
  tools: string[];
}

interface PropType {
  dataArr: DataType[];
}

const Home: NextPage<PropType> = ({ dataArr }) => {
  const { tags, dispatch } = useContext(TagsContext);

  const [filterDataArr, setFilteredDataArr] = useState<DataType[]>([]);

  useEffect(() => {
    if (tags.length > 0) {
      setFilteredDataArr(dataArr.filter(filterCallback));
    } else {
      setFilteredDataArr(dataArr);
    }

    function filterCallback(data: DataType) {
      const tempArr = [data.role, data.level];

      if (data.languages) tempArr.push(...data.languages);
      if (data.tools) tempArr.push(...data.tools);

      return tags.every((tag) => tempArr.includes(tag));
    }
  }, [dataArr, tags]);
  return (
    <>
      <Head>
        <title>Job Listing | FEM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute top-0 left-0 w-full h-40 bg-no-repeat bg-cover bg-primary bg-header-mobile md:bg-header-desktop"></div>
      <main className="relative z-10 max-w-5xl pt-32 mx-auto w-90w md:px-6">
        {tags.length > 0 && (
          <div className="flex items-center gap-2 px-4 py-5 bg-white rounded-md shadow-xl">
            <div className="flex flex-wrap flex-1 gap-2">
              {tags.map((item) => (
                <FilterItem key={item} item={item} />
              ))}
            </div>
            <div className="font-bold text-cyan-gray hover:text-cyan-gray-dark">
              <button onClick={() => dispatch(clearTagsAction())}>Clear</button>
            </div>
          </div>
        )}

        {/* List */}
        <div className="mt-20">
          {filterDataArr.map((data) => (
            <ListItem key={data.id} data={data} />
          ))}{" "}
        </div>
      </main>

      <Footer />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const filePath = path.join(process.cwd(), "data.json");
  const jsonData = await fs.readFile(filePath);
  const data = JSON.parse(jsonData.toString());

  return {
    props: {
      dataArr: data,
    },
  };
};
